Repository Belikhun/ctms-plus, pull requests merged in 2021-06, with the labels that each got.

#28 🏓 Thêm trang chi tiết của dịch vụ payask
  static/services/css/base.css
  static/services/css/payask.css
  static/services/js/script.js
  static/services/payask.html
Labels: documentation, enhancement

#31 🔮 Thêm scrollbar tùy chỉnh vào trang thông tin payask
  static/services/css/base.css
  static/services/css/payask.css
  static/services/payask.html
Labels: documentation, enhancement

#33 🍣 Thêm tính năng xem danh sách lịch thi
  assets/js/belibrary.js
  static/css/core.css
  static/js/api.js
  static/js/core.js
Labels: api:tests, enhancement, module:screen, screen:tests

#36 📐 add smenu left alignment
  assets/css/navbar.css
  assets/css/smenu.css
  assets/js/navbar.js
  assets/js/smenu.js
  static/css/core.css
  static/js/core.js
Labels: enhancement, priority:medium

#37 🎯 scrollable: fix clamping thumb issue
  .gitignore
  assets/js/scrollable.js
  build/test.py
Labels: bug, priority:medium

#38 ⚽ screen: show loading error in overlay
  assets/js/editor.js
  assets/js/scrollable.js
  static/js/api.js
  static/js/core.js
Labels: enhancement, module:screen
