Repository Belikhun/ctms-plus, pull requests merged in 2021-05, with the labels that each got.

#1 🧶 update issue template
  .github/ISSUE_TEMPLATE/ask.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#2 🎃 Fix some code styling issues
  LICENSE
  assets/css/default.css
  assets/css/input.css
  build/build.py
  build/deploy.sh
  static/css/core.css
Labels: enhancement

#5 ⛳ update README
  README.md
Labels: documentation

#6 🔮 Hiển thị danh sách kết quả học tập
  static/css/core.css
  static/js/api.js
  static/js/core.js
Labels: enhancement, module:screen

#10 ⛳ fix date parsing error
  static/js/api.js
Labels: api:services, bug, good first issue

#9 🧶 chuyển đường dẫn tuyệt đối thành tương đối
  index.html
  license.html
  static/js/core.js
Labels: bug

#13 🍰 add browser test
  .github/workflows/build.yml
  .github/workflows/test.yml
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  build/lib/log.py
  build/test.py
  static/js/splash.js
Labels: enhancement

#15 🛠 fix building process
  .github/workflows/build.yml
Labels: bug

#16 🕑 fix slow startup time
  static/js/core.js
Labels: bug, good first issue

#17 🥃 userSettings: rename illegal key
  static/js/core.js
Labels: bug

#18 🍞 fix results screen not able to scroll on mobile
  static/css/core.css
Labels: bug, good first issue, module:screen

#24 🧀 api.logout: fix cannot logout sometimes
  static/js/api.js
Labels: api:logout, bug

#25 🎨 implement point grading in results screen
  static/css/core.css
  static/js/api.js
  static/js/core.js
Labels: api:results, enhancement, screen:results
